import sys
import subprocess
import os

# List of libraries we detected in the codebase
TARGET_PACKAGES = [
    "flet",
    "requests",
    "aiohttp",
    "beautifulsoup4",
    "playwright",
    "PyJWT",
    "dnspython",
    "colorama",
    "Pillow",
    "packaging",
    "SQLAlchemy",
    "psycopg2-binary"
]

def freeze_current_env():
    print(f"Python: {sys.executable}")
    print("Scanning installed packages using 'pip freeze'...")
    
    try:
        # Run pip freeze
        result = subprocess.run(
            [sys.executable, "-m", "pip", "freeze"],
            capture_output=True,
            text=True,
            check=True
        )
        installed_lines = result.stdout.splitlines()
    except subprocess.CalledProcessError as e:
        print(f"❌ Error running pip freeze: {e}")
        return
    except Exception as e:
        print(f"❌ Unexpected error: {e}")
        return

    # Create a map for case-insensitive lookup: lower_name -> actual_line
    installed_map = {}
    for line in installed_lines:
        if "==" in line:
            name = line.split("==")[0]
            installed_map[name.lower()] = line
        elif "@" in line: # Handle direct URL installs if any
            pass 

    found = []
    missing = []
    
    content = []
    content.append("# Generated by Lockon Audit Tool")
    content.append("# Based on CURRENTLY INSTALLED versions in this environment")
    content.append("")
    
    for target in TARGET_PACKAGES:
        key = target.lower()
        
        # Handle common aliases in our target list vs pip output
        # e.g. code uses bs4, pip uses beautifulsoup4 (already handled by Target List having correct names)
        
        if key in installed_map:
            line = installed_map[key]
            found.append(line)
            content.append(line)
            print(f"✅ Found: {line}")
        else:
            missing.append(target)
            print(f"❌ Missing: {target}")
            content.append(f"# {target} # Not found in current env")

    with open("requirements.txt", "w", encoding="utf-8") as f:
        f.write("\n".join(content))
    
    print("\n" + "="*50)
    print(f"Updated requirements.txt with {len(found)} pinned versions.")
    if missing:
        print(f"Warning: {len(missing)} packages were not found.")
    print("="*50)

if __name__ == "__main__":
    freeze_current_env()
